# 墨记 - PowerShell 构建脚本
# 使用 UTF-8 编码构建，避免中文乱码

# 设置 UTF-8 编码
[Console]::OutputEncoding = [System.Text.Encoding]::UTF8
$OutputEncoding = [System.Text.Encoding]::UTF8

# 设置环境变量
$env:NODE_OPTIONS = "--experimental-specifier-resolution=node"
$env:VITE_CJS_IGNORE_WARNING = "true"

Write-Host "Building Ink Diary..." -ForegroundColor Cyan
Write-Host ""

# 执行构建
npm run build

if ($LASTEXITCODE -eq 0) {
    Write-Host ""
    Write-Host "Build successful!" -ForegroundColor Green
    Write-Host ""
    
    # 生成 Cloudflare Pages 配置文件
    Write-Host "Generating Cloudflare Pages config..." -ForegroundColor Cyan
    
    # 使用数组逐行构建内容
    $lines = @()
    $lines += '# Cloudflare Pages Configuration'
    $lines += '# Auto-generated by build.ps1'
    $lines += '# https://developers.cloudflare.com/pages/platform/headers/'
    $lines += ''
    $lines += 'name = "ink-diary"'
    $lines += 'compatibility_date = "2024-01-01"'
    $lines += ''
    $lines += '[build]'
    $lines += 'command = "npm run build"'
    $lines += 'output_directory = "dist"'
    $lines += ''
    $lines += '[build.environment]'
    $lines += 'NODE_VERSION = "20"'
    $lines += ''
    $lines += '# SPA redirect rules'
    $lines += '[[redirects]]'
    $lines += 'from = "/*"'
    $lines += 'to = "/index.html"'
    $lines += 'status = 200'
    $lines += ''
    $lines += '# manifest.json headers'
    $lines += '[[headers]]'
    $lines += 'for = "/manifest.json"'
    $lines += '[headers.values]'
    $lines += 'Content-Type = "application/manifest+json"'
    $lines += 'Access-Control-Allow-Origin = "*"'
    $lines += ''
    $lines += '# Service Worker no-cache'
    $lines += '[[headers]]'
    $lines += 'for = "/service-worker.js"'
    $lines += '[headers.values]'
    $lines += 'Cache-Control = "no-cache"'
    $lines += ''
    $lines += '# JS files long cache'
    $lines += '[[headers]]'
    $lines += 'for = "/*.js"'
    $lines += '[headers.values]'
    $lines += 'Cache-Control = "public, max-age=31536000, immutable"'
    $lines += ''
    $lines += '# CSS files long cache'
    $lines += '[[headers]]'
    $lines += 'for = "/*.css"'
    $lines += '[headers.values]'
    $lines += 'Cache-Control = "public, max-age=31536000, immutable"'
    $lines += ''
    $lines += '# Font files long cache'
    $lines += '[[headers]]'
    $lines += 'for = "/*.woff2"'
    $lines += '[headers.values]'
    $lines += 'Cache-Control = "public, max-age=31536000, immutable"'
    $lines += ''
    $lines += '# Image files long cache'
    $lines += '[[headers]]'
    $lines += 'for = "/*.png"'
    $lines += '[headers.values]'
    $lines += 'Cache-Control = "public, max-age=31536000, immutable"'
    $lines += ''
    $lines += '[[headers]]'
    $lines += 'for = "/*.svg"'
    $lines += '[headers.values]'
    $lines += 'Cache-Control = "public, max-age=31536000, immutable"'
    $lines += ''
    $lines += '[[headers]]'
    $lines += 'for = "/*.ico"'
    $lines += '[headers.values]'
    $lines += 'Cache-Control = "public, max-age=31536000, immutable"'
    
    $wranglerContent = $lines -join "`n"
    
    $wranglerContent | Out-File -FilePath "wrangler.toml" -Encoding UTF8
    Write-Host "wrangler.toml generated!" -ForegroundColor Green
    Write-Host ""
    Write-Host "Output: dist/"
    Write-Host "Preview: npx serve dist"
    Write-Host ""
    Write-Host "Cloudflare Pages Deploy:" -ForegroundColor Cyan
    Write-Host "   1. https://dash.cloudflare.com/pages"
    Write-Host "   2. Connect GitHub repo"
    Write-Host "   3. Or: wrangler pages deploy dist"
} else {
    Write-Host ""
    Write-Host "Build failed!" -ForegroundColor Red
    exit 1
}
